apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "repl-05"

spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:22.3

  configuration:
    settings:
      macros/replicated_shards_cluster: "replicated"
    users:
      # change the default password will cause auth failure of distributed read
      # default/password: admin
      analytics/password: admin
      analytics/profile: default
      analytics/quota: default
      analytics/networks/ip: "::/0"
    zookeeper:
      nodes:
        - host: my-zookeeper.zoons
    clusters:
      - name: replicated
        layout:
          shardsCount: 2
          replicasCount: 2

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    podTemplates:
      - name: clickhouse:22.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
